# Generated by Django 4.0.5 on 2022-06-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erlangb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erlangb',
            name='answer',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='erlangb',
            name='arrivalRate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='erlangb',
            name='channelNum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='erlangb',
            name='holdTime',
            field=models.FloatField(default=0),
        ),
    ]
